server:
  # undertow
  undertow:
    accesslog:
      dir: ./log/ # Undertow access log directory.
      enabled: false # Enable access log.
      pattern: '%t [%I] %a %r %s (%b Byte) (%T ms)' # Format pattern for access logs.
      prefix: access_log. # Log file name prefix.
      rotate: true # Enable access log rotation.
      suffix: log # Log file name suffix.
    buffer-size: # Size of each buffer in bytes.
    buffers-per-region: # Number of buffer per region.
    direct-buffers: # Allocate buffers outside the Java heap.
    io-threads: # Number of I/O threads to create for the worker.
    max-http-post-size: 0 # Maximum size in bytes of the HTTP post content.
    worker-threads: # Number of worker threads.
  port: 9001
  servlet:
    context-path:

# rabbitmq相关配置
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456

#消息确认机制
    # 消费手动确认
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          # 消息多次消费的间隔1秒
          initial-interval: 1000
        # 设置为false，会丢弃消息或者重新发布到死信队列
        default-requeue-rejected: false
    publisher-confirms: true #开启消息确认机制
    publisher-returns: true #支持消息发送失败返回队列


